name: Tag New Version
description: >
  Tag new versions in your repository based on changes to their contents, such
  as the version specified in a `package.json` or `gemspec`.
author: Dan Freeman
inputs:
  version-command:
    description: >
      A shell command whose output when executed will be considered the version
      of your repository for the commit at which it's currently checked out.
  tag-template:
    description: >
      A template for producing a tag name from the current version of your
      repository, replacing '{VERSION}' with the deteced version.
    default: 'v{VERSION}'
runs:
  using: 'node12'
  main: 'dist/index.js'
